# Generated by Django 4.1.3 on 2022-12-10 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raterapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='category_id',
        ),
        migrations.AlterField(
            model_name='gamecategory',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='raterapi.game'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='raterapi.game'),
        ),
    ]
